version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço
    image: estevaotl/node-ezops:latest
    restart: always
    environment:
      - MONGODB_URL=${MONGODB_URL}
    ports:
      - "3000:3000" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    networks:
      - mongo