name: CI/CD

on: 
  push:
    branches: ["main"]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3.4.0

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: sudo docker stop c6b 
                  sudo docker image rm f15 -f
                  sudo docker pull estevaotl/testezops:latest
                  sudo docker run -p 3000:3000 -d estevaotl/testezops
          
      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
      
      - name: Contrução da imagem Docker
        uses: docker/build-push-action@v4.0.0
        with: 
          context: ./
          file: ./Dockerfile
          push: true
          tags: estevaotl/testezops:latest
          

