name: Pipeline

on: 
  push:
    branches: ["main"]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3.4.0

      - name: Autenticação no Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Construção e push da imagem Docker
        uses: docker/build-push-action@v4.0.0
        with: 
          context: .
          file: Dockerfile
          push: true
          tags: estevaotl/testezops:latest

      - name: Execução de comandos SSH usando senha
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USERNAME_SERVER }}
          password: ${{ secrets.PASSWORD_SERVER }}
          port: ${{ secrets.PORT_SERVER }}
          key: ${{ secrets.PRIVATE_KEY_SERVER }}
          script: |
                  cd /home/ubuntu/ezops
                  sudo docker stop estevao
                  sudo docker pull estevaotl/testezops:latest
                  sudo docker run -p 3000:3000 --name estevao -d estevaotl/testezops:latest
